title: Final Fantasy XI Guides
description: A site hosting a collection of guides made by members of the Final Fantasy XI community for other community members.
logo: "assets/images/global/header/logo.png"
theme: just-the-docs
color_scheme: dark
search_enabled: true

url: https://ffxi-guides.github.io

aux_links:
  Windower: https://windower.net/
  Ashita: https://docs.ashitaxi.com/
  BG Wiki: https://bg-wiki.com
  FFXIAH: https://ffxiah.com/

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

collections:
  general:
    output: true
  battle-content:
    output: true
  crafting:
    output: true
  windower:
    output: true
  ashita:
    output: true
  troubleshooting:
    output: true
  

just_the_docs:
  collections:
    general:
      name: General
      nav_fold: false
    battle-content:
      name: Battle Content
      nav_fold: false
    crafting:
      name: Crafting
      nav_fold: false
    windower:
      name: Windower
      nav_fold: false
    ashita:
      name: Ashita
      nav_fold: false
    troubleshooting:
      name: Troubleshooting
      nav_fold: false
